// <auto-generated />
using System;
using BabyShopping_FinalAss.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BabyShopping_FinalAss.Data.Migrations
{
    [DbContext(typeof(BabyCareContext))]
    [Migration("20241108051247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Accounts", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountType = 1,
                            Email = "thanhthao110889@gmail.com",
                            Password = "12345678",
                            Phone = "0982345167",
                            Status = 1,
                            Username = "thaolent"
                        },
                        new
                        {
                            AccountId = 2,
                            AccountType = 1,
                            Email = "kisshoang@gmail.com",
                            Password = "12345678",
                            Phone = "0982345168",
                            Status = 1,
                            Username = "dungdq"
                        });
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Diapers",
                            Description = "Diaper for infant and baby"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Powdered Milk",
                            Description = "A dairy product made by evaporating milk to dryness"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Reconstituted milk",
                            Description = "Mixing milk powder with water to create liquid milk"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Baby Food",
                            Description = "This food is specifically made to meet the nutritional needs of infants and toddlers, ensuring they get the essential vitamins and minerals for proper growth and development"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Vitamins",
                            Description = " vitamins are essential for their growth and development"
                        });
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AveragePoint")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AveragePoint = 7.5m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 403, DateTimeKind.Local).AddTicks(4088),
                            Description = "Platinum",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\Huggies.jpg",
                            Price = 195000.0m,
                            ProductName = "Huggies Nature Made",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(6652)
                        },
                        new
                        {
                            ProductId = 2,
                            AveragePoint = 5.0m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7832),
                            Description = "Bobby for baby",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\bobby.jpg",
                            Price = 189900.0m,
                            ProductName = "Bobby",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7834)
                        },
                        new
                        {
                            ProductId = 3,
                            AveragePoint = 9.0m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7836),
                            Description = "Gooby Extra Newborn Little ",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\gooby.jpg",
                            Price = 205000.0m,
                            ProductName = "Gooby",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7836)
                        },
                        new
                        {
                            ProductId = 4,
                            AveragePoint = 7.2m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7838),
                            Description = "Bland, soft fabric. - Ultra-soft fabric using the super-microfiber ",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\nabizam.jpg",
                            Price = 234098.0m,
                            ProductName = "Nabizam",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7838)
                        },
                        new
                        {
                            ProductId = 5,
                            AveragePoint = 6.1m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7864),
                            Description = "MAMOGOM Premium CARE ORGANIC KOREAN PREMIUM CARE  ",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\mamogom.jpg",
                            Price = 245000.0m,
                            ProductName = "Mamogom",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7865)
                        },
                        new
                        {
                            ProductId = 6,
                            AveragePoint = 7.5m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7866),
                            Description = "Aptamil NewZeland",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\aptamil_bac.jpg",
                            Price = 195000.0m,
                            ProductName = "Aptamil",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7867)
                        },
                        new
                        {
                            ProductId = 7,
                            AveragePoint = 5.0m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7869),
                            Description = "For infant",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\blackmore.jpg",
                            Price = 189900.0m,
                            ProductName = "Blackmores",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7870)
                        },
                        new
                        {
                            ProductId = 8,
                            AveragePoint = 9.0m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7871),
                            Description = "Colos for baby",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\colosbaby.jpg",
                            Price = 205000.0m,
                            ProductName = "ColosBaby",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7872)
                        },
                        new
                        {
                            ProductId = 9,
                            AveragePoint = 7.2m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7873),
                            Description = "Well-cooked, pureed legumes such as beans, lentils and chickpeas.",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\enfamil.jpg",
                            Price = 234098.0m,
                            ProductName = "Enfamil A+",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7874)
                        },
                        new
                        {
                            ProductId = 10,
                            AveragePoint = 6.1m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7875),
                            Description = "HiPP becomes Germany's third company and first food manufacturer",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\hipp.jpg",
                            Price = 245000.0m,
                            ProductName = "HiPP",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7876)
                        },
                        new
                        {
                            ProductId = 11,
                            AveragePoint = 7.5m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7877),
                            Description = "Abott Grow",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\abottgrow.jpg",
                            Price = 195000.0m,
                            ProductName = "Abott Grow",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7878)
                        },
                        new
                        {
                            ProductId = 12,
                            AveragePoint = 5.6m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7879),
                            Description = "Aptakid",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\aptakid.jpg",
                            Price = 189900.0m,
                            ProductName = "Aptakid",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7892)
                        },
                        new
                        {
                            ProductId = 13,
                            AveragePoint = 4.0m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7894),
                            Description = "Colos for baby",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\colosbaby.jpg",
                            Price = 205000.0m,
                            ProductName = "ColosBaby",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7895)
                        },
                        new
                        {
                            ProductId = 14,
                            AveragePoint = 7.4m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7896),
                            Description = "DalatMilk",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\dalatmilk.jpg",
                            Price = 123000.0m,
                            ProductName = "DalatMilk",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7897)
                        },
                        new
                        {
                            ProductId = 15,
                            AveragePoint = 9.8m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7898),
                            Description = "Vinamil Green farm",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\vinamilk xanh.jpg",
                            Price = 134000.0m,
                            ProductName = "Vinamilk",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7899)
                        },
                        new
                        {
                            ProductId = 16,
                            AveragePoint = 7.5m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7900),
                            Description = "Banh an dam",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\banhandamGerber.jpg",
                            Price = 195000.0m,
                            ProductName = "Gerber Puffs",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7901)
                        },
                        new
                        {
                            ProductId = 17,
                            AveragePoint = 5.6m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7902),
                            Description = "Bot an dam vi lua mach",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\botbiokid.jpg",
                            Price = 189900.0m,
                            ProductName = "BioKids",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7903)
                        },
                        new
                        {
                            ProductId = 18,
                            AveragePoint = 4.0m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7970),
                            Description = "Bot an dam vij sua",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\botHeinz.jpg",
                            Price = 205000.0m,
                            ProductName = "Bot Heinz",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7971)
                        },
                        new
                        {
                            ProductId = 19,
                            AveragePoint = 7.4m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7973),
                            Description = "Bot an dam Hipp",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\botHipp.jpg",
                            Price = 123000.0m,
                            ProductName = "Bot HiPP Organic",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7973)
                        },
                        new
                        {
                            ProductId = 20,
                            AveragePoint = 9.8m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7991),
                            Description = "Vang sua trai cay",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\vangsuahoff.jpg",
                            Price = 134000.0m,
                            ProductName = "Vang sua Hoff",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7991)
                        },
                        new
                        {
                            ProductId = 21,
                            AveragePoint = 7.5m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7993),
                            Description = "Men tieu hoa",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\biogaia.jpg",
                            Price = 195000.0m,
                            ProductName = "BioGaia",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7994)
                        },
                        new
                        {
                            ProductId = 22,
                            AveragePoint = 5.6m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7995),
                            Description = "D3K2",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\sunday natural.jpg",
                            Price = 189900.0m,
                            ProductName = "Sunday Natural",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7996)
                        },
                        new
                        {
                            ProductId = 23,
                            AveragePoint = 4.0m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7997),
                            Description = "An ngon ngu ngon",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\fitobimbi.jpg",
                            Price = 205000.0m,
                            ProductName = "Fitobimbi",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7998)
                        },
                        new
                        {
                            ProductId = 24,
                            AveragePoint = 7.4m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(7999),
                            Description = "MultiVitamins",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\pediakid.jpg",
                            Price = 123000.0m,
                            ProductName = "PediaKid",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(8000)
                        },
                        new
                        {
                            ProductId = 25,
                            AveragePoint = 9.8m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(8001),
                            Description = "Probiotic",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\pribiotic.jpg",
                            Price = 134000.0m,
                            ProductName = "Kid Smart drops",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 8, 12, 12, 46, 404, DateTimeKind.Local).AddTicks(8002)
                        });
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Ratings", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Point")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RatingId");

                    b.HasIndex("ProductId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Comment = "This iss rating for product 1",
                            Point = 5,
                            ProductId = 1
                        },
                        new
                        {
                            RatingId = 2,
                            Comment = "This iss rating for product 6",
                            Point = 7,
                            ProductId = 6
                        },
                        new
                        {
                            RatingId = 3,
                            Comment = "This iss rating for product 10",
                            Point = 8,
                            ProductId = 10
                        },
                        new
                        {
                            RatingId = 4,
                            Comment = "This iss rating for product 19",
                            Point = 6,
                            ProductId = 19
                        },
                        new
                        {
                            RatingId = 5,
                            Comment = "This iss rating for product 22",
                            Point = 9,
                            ProductId = 22
                        });
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Products", b =>
                {
                    b.HasOne("BabyShopping_FinalAss.Entities.Categories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Ratings", b =>
                {
                    b.HasOne("BabyShopping_FinalAss.Entities.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
