// <auto-generated />
using System;
using BabyShopping_FinalAss.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BabyShopping_FinalAss.Data.Migrations
{
    [DbContext(typeof(BabyCareContext))]
    partial class BabyCareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Accounts", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountType = 1,
                            Email = "thanhthao110889@gmail.com",
                            Password = "12345678",
                            Phone = "0982345167",
                            Status = 1,
                            Username = "thaolent"
                        },
                        new
                        {
                            AccountId = 2,
                            AccountType = 1,
                            Email = "kisshoang@gmail.com",
                            Password = "12345678",
                            Phone = "0982345168",
                            Status = 1,
                            Username = "dungdq"
                        });
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Diapers",
                            Description = "Diaper for infant and baby"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Powdered Milk",
                            Description = "A dairy product made by evaporating milk to dryness"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Reconstituted milk",
                            Description = "Mixing milk powder with water to create liquid milk"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Baby Food",
                            Description = "This food is specifically made to meet the nutritional needs of infants and toddlers, ensuring they get the essential vitamins and minerals for proper growth and development"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Vitamins",
                            Description = " vitamins are essential for their growth and development"
                        });
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AveragePoint")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AveragePoint = 7.5m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 863, DateTimeKind.Local).AddTicks(6080),
                            Description = "Platinum",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\Huggies.jpg",
                            Price = 195000.0m,
                            ProductName = "Huggies Nature Made",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(7168)
                        },
                        new
                        {
                            ProductId = 2,
                            AveragePoint = 5.0m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8282),
                            Description = "Bobby for baby",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\bobby.jpg",
                            Price = 189900.0m,
                            ProductName = "Bobby",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8300)
                        },
                        new
                        {
                            ProductId = 3,
                            AveragePoint = 9.0m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8301),
                            Description = "Gooby Extra Newborn Little ",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\gooby.jpg",
                            Price = 205000.0m,
                            ProductName = "Gooby",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8301)
                        },
                        new
                        {
                            ProductId = 4,
                            AveragePoint = 7.2m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8303),
                            Description = "Bland, soft fabric. - Ultra-soft fabric using the super-microfiber ",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\nabizam.jpg",
                            Price = 234098.0m,
                            ProductName = "Nabizam",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8303)
                        },
                        new
                        {
                            ProductId = 5,
                            AveragePoint = 6.1m,
                            CategoryId = 1,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8305),
                            Description = "MAMOGOM Premium CARE ORGANIC KOREAN PREMIUM CARE  ",
                            Image = "D:\\.NET\\BabyShopping_Image\\Diaper\\mamogom.jpg",
                            Price = 245000.0m,
                            ProductName = "Mamogom",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8305)
                        },
                        new
                        {
                            ProductId = 6,
                            AveragePoint = 7.5m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8306),
                            Description = "Aptamil NewZeland",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\aptamil_bac.jpg",
                            Price = 195000.0m,
                            ProductName = "Aptamil",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8307)
                        },
                        new
                        {
                            ProductId = 7,
                            AveragePoint = 5.0m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8308),
                            Description = "For infant",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\blackmore.jpg",
                            Price = 189900.0m,
                            ProductName = "Blackmores",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8308)
                        },
                        new
                        {
                            ProductId = 8,
                            AveragePoint = 9.0m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8310),
                            Description = "Colos for baby",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\colosbaby.jpg",
                            Price = 205000.0m,
                            ProductName = "ColosBaby",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8310)
                        },
                        new
                        {
                            ProductId = 9,
                            AveragePoint = 7.2m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8311),
                            Description = "Well-cooked, pureed legumes such as beans, lentils and chickpeas.",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\enfamil.jpg",
                            Price = 234098.0m,
                            ProductName = "Enfamil A+",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8312)
                        },
                        new
                        {
                            ProductId = 10,
                            AveragePoint = 6.1m,
                            CategoryId = 2,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8322),
                            Description = "HiPP becomes Germany's third company and first food manufacturer",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Powdered milk\\hipp.jpg",
                            Price = 245000.0m,
                            ProductName = "HiPP",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8323)
                        },
                        new
                        {
                            ProductId = 11,
                            AveragePoint = 7.5m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8324),
                            Description = "Abott Grow",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\abottgrow.jpg",
                            Price = 195000.0m,
                            ProductName = "Abott Grow",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8324)
                        },
                        new
                        {
                            ProductId = 12,
                            AveragePoint = 5.6m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8326),
                            Description = "Aptakid",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\aptakid.jpg",
                            Price = 189900.0m,
                            ProductName = "Aptakid",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8326)
                        },
                        new
                        {
                            ProductId = 13,
                            AveragePoint = 4.0m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8327),
                            Description = "Colos for baby",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\colosbaby.jpg",
                            Price = 205000.0m,
                            ProductName = "ColosBaby",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8328)
                        },
                        new
                        {
                            ProductId = 14,
                            AveragePoint = 7.4m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8329),
                            Description = "DalatMilk",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\dalatmilk.jpg",
                            Price = 123000.0m,
                            ProductName = "DalatMilk",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8330)
                        },
                        new
                        {
                            ProductId = 15,
                            AveragePoint = 9.8m,
                            CategoryId = 3,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8331),
                            Description = "Vinamil Green farm",
                            Image = "D:\\.NET\\BabyShopping_Image\\Milk\\Liquid milk\\vinamilk xanh.jpg",
                            Price = 134000.0m,
                            ProductName = "Vinamilk",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8331)
                        },
                        new
                        {
                            ProductId = 16,
                            AveragePoint = 7.5m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8333),
                            Description = "Banh an dam",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\banhandamGerber.jpg",
                            Price = 195000.0m,
                            ProductName = "Gerber Puffs",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8333)
                        },
                        new
                        {
                            ProductId = 17,
                            AveragePoint = 5.6m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8335),
                            Description = "Bot an dam vi lua mach",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\botbiokid.jpg",
                            Price = 189900.0m,
                            ProductName = "BioKids",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8335)
                        },
                        new
                        {
                            ProductId = 18,
                            AveragePoint = 4.0m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8344),
                            Description = "Bot an dam vij sua",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\botHeinz.jpg",
                            Price = 205000.0m,
                            ProductName = "Bot Heinz",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8344)
                        },
                        new
                        {
                            ProductId = 19,
                            AveragePoint = 7.4m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8346),
                            Description = "Bot an dam Hipp",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\botHipp.jpg",
                            Price = 123000.0m,
                            ProductName = "Bot HiPP Organic",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8346)
                        },
                        new
                        {
                            ProductId = 20,
                            AveragePoint = 9.8m,
                            CategoryId = 4,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8348),
                            Description = "Vang sua trai cay",
                            Image = "D:\\.NET\\BabyShopping_Image\\Baby Food\\vangsuahoff.jpg",
                            Price = 134000.0m,
                            ProductName = "Vang sua Hoff",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8348)
                        },
                        new
                        {
                            ProductId = 21,
                            AveragePoint = 7.5m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8350),
                            Description = "Men tieu hoa",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\biogaia.jpg",
                            Price = 195000.0m,
                            ProductName = "BioGaia",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8350)
                        },
                        new
                        {
                            ProductId = 22,
                            AveragePoint = 5.6m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8351),
                            Description = "D3K2",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\sunday natural.jpg",
                            Price = 189900.0m,
                            ProductName = "Sunday Natural",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8352)
                        },
                        new
                        {
                            ProductId = 23,
                            AveragePoint = 4.0m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8353),
                            Description = "An ngon ngu ngon",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\fitobimbi.jpg",
                            Price = 205000.0m,
                            ProductName = "Fitobimbi",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8353)
                        },
                        new
                        {
                            ProductId = 24,
                            AveragePoint = 7.4m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8354),
                            Description = "MultiVitamins",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\pediakid.jpg",
                            Price = 123000.0m,
                            ProductName = "PediaKid",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8355)
                        },
                        new
                        {
                            ProductId = 25,
                            AveragePoint = 9.8m,
                            CategoryId = 5,
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8357),
                            Description = "Probiotic",
                            Image = "D:\\.NET\\BabyShopping_Image\\Vitamin\\pribiotic.jpg",
                            Price = 134000.0m,
                            ProductName = "Kid Smart drops",
                            UpdatedBy = "Admin",
                            UpdatedDate = new DateTime(2024, 11, 6, 22, 6, 7, 864, DateTimeKind.Local).AddTicks(8357)
                        });
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Ratings", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Point")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefProductIdProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RatingId");

                    b.HasIndex("RefProductIdProductId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Comment = "This iss rating for product 1",
                            Point = 5,
                            RefProductIdProductId = 1
                        },
                        new
                        {
                            RatingId = 2,
                            Comment = "This iss rating for product 6",
                            Point = 7,
                            RefProductIdProductId = 6
                        },
                        new
                        {
                            RatingId = 3,
                            Comment = "This iss rating for product 10",
                            Point = 8,
                            RefProductIdProductId = 10
                        },
                        new
                        {
                            RatingId = 4,
                            Comment = "This iss rating for product 19",
                            Point = 6,
                            RefProductIdProductId = 19
                        },
                        new
                        {
                            RatingId = 5,
                            Comment = "This iss rating for product 22",
                            Point = 9,
                            RefProductIdProductId = 22
                        });
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Products", b =>
                {
                    b.HasOne("BabyShopping_FinalAss.Entities.Categories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BabyShopping_FinalAss.Entities.Ratings", b =>
                {
                    b.HasOne("BabyShopping_FinalAss.Entities.Products", "RefProductId")
                        .WithMany()
                        .HasForeignKey("RefProductIdProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
